name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-push-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4

      - name: Build and push
        if: github.event_name != 'pull_request'
        run: |
          buildx build --platform linux/arm/v7 -t ghcr.io/${{ github.repository }}-armv7:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-armv7:latest .
          buildx push --platform linux/arm/v7 -t ghcr.io/${{ github.repository }}-armv7:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-armv7:latest .
          buildx build --platform linux/arm64 -t ghcr.io/${{ github.repository }}-arm64:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-arm64:latest .
          buildx push --platform linux/arm64 -t ghcr.io/${{ github.repository }}-arm64:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-arm64:latest .
          buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository }}-amd64:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-amd64:latest .
          buildx push --platform linux/amd64 -t ghcr.io/${{ github.repository }}-amd64:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-amd64:latest .
          buildx build --platform linux/s390x -t ghcr.io/${{ github.repository }}-s390x:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-s390x:latest .
          buildx push --platform linux/s390x -t ghcr.io/${{ github.repository }}-s390x:${{ steps.meta.outputs.tags }} -t ghcr.io/${{ github.repository }}-s390x:latest .